apiVersion: v1
kind: LimitRange
metadata:
  name: my-lr
  namespace: mynamespace
spec:
  limits:
    - default:
        cpu: 1
        memory: 500Mi
      defaultRequest:
        cpu: 0.5
        memory: 250Mi
      type: Container
