#kubectl label nodes <node-name> <label-key>=<label-value>(command to label a node)


apiVersion: v1
kind: Pod
metadata: 
  name: jenkins
  labels:
    app: jenkins
spec:
  containers: 
    - name: jenkins
      image: jenkins/jenkins:lts
  nodeSelector:
    node: my_worker1
