apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-ebs-dynamic
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
